ALTER TABLE questions ADD COLUMN topic TEXT NOT NULL DEFAULT '';
ALTER TABLE questions ADD COLUMN hint TEXT NOT NULL DEFAULT '';
ALTER TABLE questions ADD COLUMN explanation TEXT NOT NULL DEFAULT '';
